시험성적, 공부시간(X) > 통과(0),실패(1)

In [27]:
import numpy as np
import tensorflow as tf

In [17]:
x = [1,2,3,5,6,7,8]
y = [1,1,1,0,0,0,0]

In [22]:
x = np.array(x).reshape((-1,1)).astype(np.float32)
y = np.array(y).reshape((-1,1)).astype(np.float32)
type(x), x.shape, x.ndim

(numpy.ndarray, (7, 1), 2)

In [114]:
w = tf.Variable(tf.random_normal(shape=[1,1]))
b = tf.Variable(0.0)
z = tf.matmul(x, w) + b 
h = tf.sigmoid(z)
cost = tf.reduce_mean(tf.square(h - y)) #MSE
predict = tf.cast(h > 0.5, tf.int32) # 모델과 상관 없습니다, 편의를 위해 사용
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict, tf.cast(y,tf.int32)), tf.int32))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [123]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [131]:
for i in range(1000):
    _, acc, co = sess.run([train, accuracy, cost])
    if i%100==0: print(i, co, acc)

0 0.042069674 1
100 0.04165447 1
200 0.041248612 1
300 0.04085178 1
400 0.040463664 1
500 0.040083975 1
600 0.039712403 1
700 0.039348714 1
800 0.038992636 1
900 0.038643908 1


In [103]:
np.set_printoptions(precision=2)
sess.run(z).reshape([-1])

array([ 2.5 ,  1.58,  0.66, -1.18, -2.1 , -3.02, -3.94], dtype=float32)

In [104]:
sess.run(h).reshape([-1])

array([0.92, 0.83, 0.66, 0.24, 0.11, 0.05, 0.02], dtype=float32)

In [80]:
sess.run(predict).reshape([-1])

array([1, 1, 1, 0, 0, 0, 0])